"""empty message

Revision ID: 7a36790734ac
Revises: f789800fda3a
Create Date: 2020-03-17 17:51:27.847534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a36790734ac'
down_revision = 'f789800fda3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'date')
    # ### end Alembic commands ###
